---

- name: ansible-role-radicale
  src: https://github.com/AnarchoTechNYC/ansible-role-radicale

- name: ansible-znc
  src: https://github.com/isaaclo123/ansible-znc

# - name: ansible-openvpn
#   src: https://github.com/isaaclo123/Stouts.openvpn

- name: ansible-role-openvpn
  src: https://github.com/isaaclo123/ansible-role-openvpn

- src: jdauphant.nginx

- src: weareinteractive.ufw

- src: thefinn93.letsencrypt
  # - src: spk.syncthing-debian
- src: escaped.Syncthing

  # - src: kyl191.openvpn

- src: smaffulli.bitlbee
  # - src: dhellman.znc-on-znc
- src: nickjj.fail2ban

# - src: Stouts.openvpn
