---

# - name: certbot packages
#   hosts: all
#   become: yes
#   tasks:
#   - name: Install certbot for nginx
#     apt:
#       name: "{{ packages }}"
#     vars:
#       packages:
#       - certbot
#       - python-certbot-nginx

- hosts: all
  become: yes
  roles:
    - role: thefinn93.letsencrypt
      letsencrypt_webroot_path: "/var/www/{{ domain }}/html"
      letsencrypt_email: "{{ email }}"
      letsencrypt_cert_domains:
        - "{{ domain }}"
      letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
      # ssl_certificate: "{{ ssl_cert_path }}"
      # ssl_certificate_key: "{{ ssl_privkey_path }}"
