---

- hosts: all
  gather_facts: true
  become: yes
  roles:
  - role: ansible-role-openvpn
    clients: "{{ openvpn_client_list }}"
    openvpn_port: "{{ openvpn_server_port }}"
    openvpn_proto: udp
    openvpn_server_hostname: "{{ domain }}"
    openvpn_dualstack: false
    openvpn_rsa_bits: 4096
    manage_firewall_rules: false
