---

# - hosts: all
#   become: yes
#   tasks:
#   - name: Install python packages for RadicaleInfCloud
#     apt:
#       name: "{{ packages }}"
#     vars:
#       packages:
#       - python3
#       - python3-pip
#
#   - name: Install infcloud
#     pip:
#       name: git+https://github.com/Unrud/RadicaleInfCloud
#       executable: pip3

- hosts: all
  become: yes
  roles:
  - role: ansible-role-radicale
    radicale_config:
      # web:
      #   type: radicale_infcloud
      server:
        hosts:
          - addr: 0.0.0.0
            port: "{{ radicale_port }}"
        dns_lookup: false
        auth:
          type: htpasswd
          htpasswd_filename: "{{ radicale_server_home_dir }}/users.htpasswd"
          htpasswd_encryption: bcrypt
          delay: 1
        rights:
          type: from_file
          file: "{{ radicale_server_home_dir }}/rights.conf"
        storage:
          type: multifilesystem
          filesystem_folder: "{{ radicale_server_home_dir }}/collections"
          filesystem_locking: true
          filesystem_fsync: true

    radicale_users:
      - name: "{{ user_name }}"
        password: "{{ radicale_password }}"
